language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

env:
  global:
    - setup=basic
  matrix:
    - laravel=5.5.*
    - laravel=5.6.*
    - laravel=5.7.*
    - laravel=dev-master
    - setup=lowest laravel=5.5.*
    - setup=lowest laravel=5.6.*
    - setup=lowest laravel=5.7.*
    - setup=lowest laravel=dev-master
    - setup=stable laravel=5.5.*
    - setup=stable laravel=5.6.*
    - setup=stable laravel=5.7.*
    - setup=stable laravel=dev-master

# HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
dist: trusty

install:
  - travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
  - vendor/bin/phpunit -c ./ --verbose

matrix:
  allow_failures:
    - php: nightly
    - env: laravel=dev-master
  fast_finish: true
