language: php
dist: xenial

php:
  - 7.2
  - 7.3

env:
  global:
    - setup=basic
  matrix:
    - laravel=^5.8
    - laravel=^6.0
    - laravel=dev-master
    - setup=stable laravel=^5.8
    - setup=stable laravel=^6.0
    - setup=stable laravel=dev-master
    - setup=lowest laravel=^5.8
    - setup=lowest laravel=^6.0
    - setup=lowest laravel=dev-master

dist: trusty

before_install:
  - if [[ $xdebug = 'true' ]] ; then phpenv config-rm xdebug.ini; fi

install:
  - travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
  - vendor/bin/phpunit -c ./ --verbose

matrix:
  fast_finish: true
