language: php
sudo: false
dist: trusty

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  global:
    - setup=basic
  matrix:
    - laravel=5.4.*
    - laravel=5.5.*

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 5.6
      env:
        - setup=lowest
        - laravel=5.4.*
    - php: 5.6
      env:
        - setup=stable
        - laravel=5.4.*
    - php: 7.0
      env:
        - setup=lowest
        - laravel=5.5.*
    - php: 7.0
      env:
        - setup=stable
        - laravel=5.5.*
  fast_finish: true
