language: php
sudo: false
dist: trusty

php:
  - 7.1
  - 7.2

env:
  global:
    - setup=basic
  matrix:
    - laravel=5.5.*
    - laravel=5.6.*
    - laravel=5.7.*

# HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
dist: trusty

cache:
  directories:
    - $HOME/.composer/cache

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest --prefer-stable --prefer-lowest; fi

script:
  - vendor/bin/phpunit

matrix:
  include:
    - php: 7.0
      env:
        - setup=basic
        - laravel=5.5.*
    - php: 7.0
      env:
        - setup=lowest
        - laravel=5.5.*
    - php: 7.0
      env:
        - setup=stable
        - laravel=5.5.*
    - php: 7.1
      env:
        - setup=lowest
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=stable
        - laravel=5.6.*
    - php: 7.1
      env:
        - setup=lowest
        - laravel=5.7.*
    - php: 7.1
      env:
        - setup=stable
        - laravel=5.7.*
  fast_finish: true
